import Head from "next/head";
import { useBeers } from "@/hooks/useBeers";
import { MasonryGrid } from "@/components/MasonryGrid";
import { BeerCard } from "@/components/BeerCard";
import { Avatar, Input } from "react-daisyui";
import Image from "next/image";
import { useState } from "react";

const Overlay = ({ show }: { show: boolean }) => {
  return (
    <div
      className={`transition-all fixed ${
        show
          ? " backdrop-blur-sm  bg-black bg-opacity-50 pointer-events-auto"
          : ""
      } z-[2] top-0 left-0 h-screen w-screen pointer-events-none`}
    ></div>
  );
};

export default function Home() {
  const beers = useBeers();

  const [showInput, setShowInput] = useState(false);

  const numberOfBeers =
    beers.data?.pages.reduce((acc, page) => acc + page.beers.length, 0) ?? 0;

  return (
    <>
      <Head>
        <title>PiwkoSzukacz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Overlay show={showInput} />
      <div className="max-w-full flex items-start ml-12 mt-6">
        <Image height={48} width={48} src="/logo.png" alt="logo" />
        <Input
          onFocus={() => {
            setShowInput(true);
          }}
          onBlur={() => {
            setShowInput(false);
          }}
          className="ml-4 pl-6 w-full z-10 shadow-sm focus:outline-none border-b-2 border-primary border-t-0 border-l-0 border-r-0 rounded-none focus:rounded"
          type="text"
          placeholder="Wyszukaj piwko 🍺"
        />
        <Avatar
          shape="circle"
          className="ml-8 mr-8  hover:shadow-lg cursor-pointer rounded-full"
          color="info"
          size="xs"
          src="https://thumbs.dreamstime.com/b/bavarian-man-oktoberfest-bavarian-man-oktoberfest-avatar-food-beer-vector-illustration-graphic-design-134351200.jpg"
        />
      </div>
      <div className="mt-14">
        <MasonryGrid
          next={() => {
            console.log("loool");
            beers.fetchNextPage();
          }}
          loader={<p>Ładowanko</p>}
          scrollThreshold={0.6}
          dataLength={numberOfBeers}
          hasMore={beers.hasNextPage ?? false}
        >
          {beers.data?.pages.map((page) =>
            page.beers.map((beer) => <BeerCard key={beer.id} beer={beer} />)
          ) ?? []}
        </MasonryGrid>
      </div>
    </>
  );
}
